### ISSUE TITLE
stopped working with angular 5

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-exemplify#9]

**Comment by hayden4c** [comment]
Confirmed. Any ETA on a fix?

**Comment by dannygoncalves** [comment]
I've also had problems running it into an NG6, do you think there could be a fix soon?

**Comment by dannygoncalves** [comment]
@hjalmers On line 272 of exemplify.directive.ts this fixes the ng5 ng6 issues, I was able to use the exemplify in both versions now.

`    try {
      if (!this.context) {
        console.log('No context set');
      }
      let markupExampleCode = this.context.constructor['__annotations__'][0];


      if (this.elementId) {
        markupExampleCode = this.parser.parseFromString(markupExampleCode.template, "text/html").getElementById(this.elementId);
      } else if (this.exemplifyId) {

        const selector = '[exemplify="' + this.exemplifyId + '"]';
        const content = this.parser.parseFromString(markupExampleCode.template, "text/html").querySelectorAll(selector);
        if (content.length > 1) {
          console.log('Exemplify warning! Multiple elements are using: "' + this.exemplifyId + '" as a identifier for the example, it should be a unique id. Returning first match.');
        }
        markupExampleCode = content[0];

      } else {
        console.log('Exemplify warning! No id set for example element, returning first match.');
        markupExampleCode = this.parser.parseFromString(markupExampleCode[0].template, "text/html").querySelectorAll('[exemplify]')[0];
      }
      if (typeof markupExampleCode === 'undefined') {
        console.log("Exemplify warning! Can't show example as the component holding the markup couldn't be found!");
        return
      }`

**Comment by hjalmers** [comment]
@dannygoncalves nice, would you be willing to make a pull request? It seems like a very easy fix so otherwise I’ll just do it myself:) I guess it’s still not working with `aot` however, but the good news is that I’ve made pretty good progress using a different method. I just need to refine it a bit before publishing it:)

**Comment by dannygoncalves** [comment]
Sure, I will open a PR

**Comment by hjalmers** [comment]
@dannygoncalves never mind the pull request I implemented your changes and I works like a charm as long as the app is not compiled using `--aot` or `--prod` but that was the case with angular 4 too:)'

I'll add some other nice feature to this lib and release a new version compatible with latest angular in a near future:)

**Comment by dannygoncalves** [comment]
Great, so it's ok to update the npm package right now?

**Comment by hjalmers** [comment]
I’m adding some other features while I’m at it and setting up Travis for CI but I’ll close this issue once the release is out and I hope it will be before the end of this week:)

**Comment by dannygoncalves** [comment]
Awesome stuff @hjalmers however one minor thing
In your documentation https://www.npmjs.com/package/angular-exemplify there is: 

`"styles": [
  "../node_modules/bootstrap/dist/css/bootstrap.css",
  "../node_modules/angular-exemplify/exemplify/css/prism-exemplify.css",
  "styles.css"
],`
But within node_modules/angular-exemplify/exemplify <-- this last folder is no more present.

**Comment by hjalmers** [comment]
@dannygoncalves thanks for noticing, I've updated the docs now:)
